spring:
  datasource:
    url: jdbc:h2:tcp://localhost:18082/~/test # test ??? ??? ??? ??? ???? ???.
    username: sa # username? password? ??? ??? ??
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # ??????? ??? ? ??????? ????? ?? ??? ??
    properties:
      hibernate:
        format_sql: true # ???? query? ???
      show-sql : true # true ?? ?, ??? JPA ??? ????.

logging.level:
  org.hibernate.SQL: debug